spring:
  application:
    name: project2
  datasource:
    url: jdbc:mysql://localhost:3306/project2?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      location: d:/sungil/98.temp/upload/
      max-request-size: 30MB
      max-file-size: 10MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: ffca64b3547f1a11dcfef2187ea330eb
            client-secret: 8DaVpaa7JHIMeXqJ7RNkAmnnwHhcTn7x
            scope: profile_nickname
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8090/login/oauth2/code/kakao
            client-name: kakao
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: id
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize
logging:
  level:
    org:
      hibernate: info
      springframework:
        security: info
    com:
      lec: debug
server:
  port: 8090
  servlet:
    encoding:
      force-response: true
      charset: utf-8
# file upload/download
path:
  upload: d:/sungil/98.temp/upload/
  download: d:/sungil/98.temp/download/
com:
  lec:
    upload:
      path: d:/sungil/98.temp/upload/
    jwt:
      secret: hello1234567890