package com.lec.project.human_resources.domain;

public enum DepartmentName {
	HUMAN_RESOURCES, MARKETING, GENERAL_AFFAIR, FINANCE, ACCOUNTING, LEGAL, CUSTOMER_SERVICE, RESEARCH_AND_DEVELOPMENT, PRODUCTION_MANAGEMENT, INFORMATION_TECHNOLOGY, DATA_ANALYSIS, INTERNATIONAL_COOPERATION
}