package com.lec.project.human_resources.domain;

public enum Position {
	CHAIRMAN, VICE_CHAIRMAN, PRESIDENT, VICE_PRESIDENT, SENIOR_VICE_PRESIDENT, EXECUTIVE_VICE_PRESIDENT, DIRECTOR, DEPARTMENT_HEAD, DEPUTY_DEPARTMENT_HEAD, MANAGER, ASSISTANT_MANAGER, STAFF, INTERN
}